services:
    laravel.test:
        container_name: 'lancore.test'
        build:
            context: ./vendor/laravel/sail/runtimes/8.5
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.5/app
        entrypoint: /dev-entrypoint.sh
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '${OCTANE_PORT:-8000}:${OCTANE_PORT:-8000}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - '../platform/dev/dev-entrypoint.sh:/dev-entrypoint.sh:ro'
        networks:
            - sail
            - lanparty

    horizon:
        container_name: 'lancore-horizon'
        build:
            context: ./vendor/laravel/sail/runtimes/8.5
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.5/app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - lanparty
        depends_on:
            - laravel.test
        command: 'php artisan horizon'
        stop_signal: SIGTERM
        stop_grace_period: 3600s
        restart: unless-stopped

    scheduler:
        container_name: 'lancore-scheduler'
        build:
            context: ./vendor/laravel/sail/runtimes/8.5
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.5/app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - lanparty
        depends_on:
            - laravel.test
        command: 'php artisan schedule:work'
        stop_signal: SIGTERM
        stop_grace_period: 30s
        restart: unless-stopped

networks:
    sail:
        driver: bridge
    lanparty:
        external: true
