/**
 * Vitest stub for the Wayfinder-generated `@/actions/*`, `@/routes/*` and
 * `@/wayfinder` modules.
 *
 * Those directories are gitignored build artifacts (generated by the Wayfinder
 * Vite plugin during `npm run build`, which needs PHP/Laravel). The Node-only
 * Vitest CI job never generates them, so any test that transitively imports a
 * route/action helper (e.g. `columns.ts` row actions, `useTwoFactorAuth`)
 * would fail to resolve. `vite.config.ts` aliases those import paths to this
 * stub under `VITEST`.
 *
 * Every property access returns the same callable proxy, so `route.url()`,
 * `Controller.method.url()`, default imports and named imports all resolve to
 * a harmless value. `__esModule` is truthy so esbuild's interop treats named
 * imports (`import { qrCode } from '@/routes/two-factor'`) as proxy props.
 */
const stub = new Proxy(function () {}, {
    get(_target, prop) {
        if (prop === '__esModule') {
            return true;
        }

        return stub;
    },
    apply() {
        return '/stubbed-wayfinder-url';
    },
});

module.exports = stub;
